anguage: android
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support
before_install:
- gem install fir-cli
script:
- "./gradlew assembleDebug"
after_deploy:
- fir p app/build/outputs/apk/app-debug.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"